main : main.o SearchCompositeWord.o
	g++ -std=c++0x -g -o main main.o SearchCompositeWord.o 
main.o : main.cpp  
	g++ -std=c++0x -g -c main.cpp
SearchCompositeWord.o : SearchCompositeWord.cpp
	g++ -std=c++0x -g -c SearchCompositeWord.cpp
